# Generated by Django 6.0.4 on 2026-04-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(max_length=500),
        ),
    ]
